export type GameMode = 'FAMILY' | 'ADULT' | 'DIRTY' | 'EXPOSING' | 'MIX';
export type Range = 'LOW' | 'MEDIUM' | 'HIGH';

export const PROMPTS: Record<GameMode, string[]> = {
    FAMILY: [
        "Wie is de grappigste?",
        "Wie kan het allerbeste koken?",
        "Wie bestelt het vaakst eten?",
        "Wie zou als eerste verdwalen?",
        "Wie is te eigenwijs om Google Maps te gebruiken?",
        "Wie is het meest sportief?",
        "Wie volgt het meeste sport?",
        "Wie is het meest rommelig?",
        "Wie maakt nooit zijn bed op?",
        "Wie kan het beste zingen?",
        "Wie zingt vals onder de douche?",
        "Wie zou je als eerst zien als president?",
        "Wie zou het langst overleven op een onbewoond eiland?",
        "Wie eet alles wat los en vast zit?",
        "Wie heeft de allerslechtste muzieksmaak?",
        "Wie is het meest verslaafd aan zijn telefoon?",
        "Wie reageert nooit op appjes?",
        "Wie is de grootste dierenvriend?",
        "Wie is het bangst voor honden?",
        "Wie kan er het beste dansen?",
        "Wie is de grootste kluns?",
        "Wie is het meest onhandig?",
        "Wie komt er altijd te laat?",
        "Wie draagt er nooit sieraden?",
        "Wie is de ideale schoonzoon/schoondochter?",
        "Wie kan het beste slijmen?",
        "Wie zou een potje armpje drukken winnen?",
        "Wie gaat er het meest naar de sportschool?",
        "Wie kan het beste geheimen bewaren?",
        "Wie zou als eerste huilen bij een film?",
        "Wie geeft de allerbeste cadeaus?",
        "Wie zou cadeaubonnen als cadeau geven?",
        "Wie heeft het grootste ochtendhumeur?",
        "Wie zou als eerste een eigen bedrijf starten?",
        "Wie vreet zich vol tijdens een film?",
        "Wie is er stiekem bang voor de donker?",
        "Wie snurkt het hardst?",
        "Wie praat er in zijn slaap?",
        "Wie wint het vaakst met bordspellen?",
        "Wie heeft de meeste schoenen?",
        "Wie lijkt het meest zijn/haar vader of moeder qua karakter?",
        "Wie lijkt het meest zijn/haar vader of moeder qua uiterlijk?",
        "Wie doet alsof ze hun leven perfect op orde hebben?",
        "Wie heeft een midlifecrisis vóór hun 40e?",
        "Wie googelt altijd zijn/haar symptomen?",
        "Wie zou spontaan een tattoo laten zetten?",
        "Wie wordt later de “coole tante/oom”?",
        "Wie maakt van elk moment een groepsfoto?",
        "Wie blijft het langst hangen na een bezoek?",
        "Wie droomt stiekem van een totaal ander leven?",
        "Wie wordt onverwacht beroemd?",
        "Wie blijft altijd zichzelf, wat er ook gebeurt?",
        "Wie vergeet altijd verjaardagen?",
        "Wie zorgt altijd dat iedereen zich welkom voelt?",
        "Wie werkt het best onder druk?",
        "Wie heeft de mooiste ogen?",
        "Wie is het knapst?",
        "Wie heeft het knapste gezicht?",
        "Wie heeft het beste haar?",
        "Wie maakt elke vakantie memorabel?",
        "Wie brengt de beste vibes?"
    ],
    ADULT: [
        "Wie is de grootste flirt?",
        "Wie wordt het snelst rood als er geflirt wordt?",
        "Wie wordt het snelst verliefd na één date?",
        "Wie geeft het meeste geld uit aan drank?",
        "Wie trakteert het vaakst?",
        "Wie heeft de allerslechtste openingszinnen?",
        "Wie wordt nooit versierd?",
        "Wie zou als eerste skinny dippen?",
        "Wie is er het meest preuts?",
        "Wie heeft de vreemdste trekjes?",
        "Wie is er stiekem heel normaal?",
        "Wie stuurt de meeste dronken appjes?",
        "Wie belt als eerste zijn ex als hij dronken is?",
        "Wie heeft het meeste zelfvertrouwen?",
        "Wie is er het braafst?",
        "Wie heeft de grootste celebrity crush?",
        "Wie zou als eerste zoenen met een collega?",
        "Wie kent zijn alcohol grens totaal niet?",
        "Wie swiped het meest naar rechts op Tinder?",
        "Wie is er het meest wanhopig op zoek naar liefde?",
        "Wie zou er als eerste trouwen op een droombestemming?",
        "Wie neemt de meeste impulsieve beslissingen?",
        "Wie valt het vaakst op 'foute' mannen/vrouwen?",
        "Wie heeft een 'type' dat niet deugt?",
        "Wie zou er als eerste een sugar daddy/mommy nemen?",
        "Wie houdt het meest van dure cadeaus?",
        "Wie is er het luidruchtigst als hij/zij dronken is?",
        "Wie wordt het snelst emotioneel van alcohol?",
        "Wie zou het snelst liegen over zijn/haar leeftijd?",
        "Wie gebruikt de meeste filters op foto's?",
        "Wie zoent het allerbeste?",
        "Wie denkt van zichzelf dat hij/zij goed kan zoenen?",
        "Wie slaapt het liefst naakt?",
        "Wie flirt het makkelijkst zonder het door te hebben?",
        "Wie heeft de meeste geheime bewonderaars?",
        "Wie is het meest zelfverzekerd op een date?",
        "Wie zou het langst single blijven?",
        "Wie krijgt de meeste aandacht in de club/bar?",
        "Wie zou het spannendst zijn op een eerste date?",
        "Wie krijgt het snelst vlinders?",
        "Wie kan niet lang single blijven?",
        "Wie is altijd het snelst dronken?"
    ],
    DIRTY: [
        "Wie zou het snelst een one-night-stand hebben?",
        "Wie zou als eerste met een beroemdheid naar bed gaan?",
        "Wie zou als eerste naakt poseren voor geld?",
        "Wie zou als eerste seks hebben op een rare plek?",
        "Wie doet het alleen maar in bed?",
        "Wie is het wildst in bed?",
        "Wie probeert het liefst nieuwe standjes?",
        "Wie heeft de meeste seksspeeltjes?",
        "Wie shopt het vaakst bij EasyToys?",
        "Wie zou als eerste een trio doen?",
        "Wie heeft de meeste fantasieën over groepsseks?",
        "Wie heeft de gekste fetisj?",
        "Wie staat het meest open voor alles?",
        "Wie zou als eerste seks hebben op een openbare plek?",
        "Wie houdt het meest van het risico om betrapt te worden?",
        "Wie is het allerbeste in dirty talk?",
        "Wie kreunt het hardst?",
        "Wie kan er het vaakst achter elkaar door met seks?",
        "Wie heeft het meeste uithoudingsvermogen?",
        "Wie doet er aan roleplay in de slaapkamer?",
        "Wie gebruikt er stiekem viagra?",
        "Wie is er het meest dominant in bed?",
        "Wie neemt het liefst de leiding in bed?",
        "Wie is er het meest onderdanig in bed?",
        "Wie laat zich het liefst vastbinden?",
        "Wie zou er als eerste een sekstape maken?",
        "Wie vindt zichzelf de koning(in) van de slaapkamer?",
        "Wie kijkt er het vaakst in de spiegel tijdens de seks?",
        "Wie zou als eerste seks hebben op de eerste date?",
        "Wie heeft de hoogste libido?",
        "Wie heeft de stoutste dromen?",
        "Wie wordt er het vaakst geil wakker?",
        "Wie masturbeert het vaakst?",
        "Wie houdt er het meest van agressief vrijen?",
        "Wie vindt een beetje pijn tijdens de seks fijn?",
        "Wie doet de ranzigste dingen in bed?",
        "Wie zou als eerste seks hebben op het werk?",
        "Wie zou als eerste seks hebben in de natuur?",
        "Wie houdt er het meest van alleen missionaris?",
        "Wie zou er strippen voor zijn/haar partner?",
        "Wie draagt er het vaakst spannend ondergoed?",
        "Wie draagt er nooit ondergoed?",
        "Wie zou er als eerste seks hebben in een auto?",
        "Wie zou er als eerste anaal doen?"
    ],
    EXPOSING: [
        "Wie kan het beste liegen?",
        "Wie roddelt het meest?",
        "Wie zou als eerste in de cel belanden?",
        "Wie heeft stiekem een oogje op de baas?",
        "Wie zou er als eerste vreemdgaan voor 1 miljoen?",
        "Wie is er het meest loyaal?",
        "Wie schept het meest op over zijn bedprestaties?",
        "Wie laat zich het makkelijkst opnaaien?",
        "Wie loopt het meeste risico op een soa?",
        "Wie heeft het meeste smetvrees?",
        "Wie wordt het vaakst wakker naast een vreemde?",
        "Wie weet de volgende ochtend het vaakst niks meer?",
        "Wie plast er vaak in het zwembad?",
        "Wie doucht er niet elke dag?",
        "Wie bemoeit zich het meest met andermans leven?",
        "Wie heeft de meeste “bijna-relaties” gehad?",
        "Wie heeft het spannendste liefdesleven?",
        "Wie speelt er vaak vals?",
        "Wie heeft de slechtste kledingstijl?",
        "Wie maakt van een kleine ruzie het meeste drama?",
        "Wie houdt er van om discussies te starten?",
        "Wie zou per ongeluk iets gênants verklappen?",
        "Wie blijft te lang in comfortzones?",
        "Wie heeft het meeste FOMO?",
        "Wie denkt onterecht dat hij/zij goed kan dansen?",
        "Wie heeft de meeste exen?",
        "Wie is er het snelst uitgekeken op een relatie?",
        "Wie zou een trio voorstellen?",
        "Wie zou zijn partner als eerst delen met een ander?",
        "Wie wordt het vaakst uitgezet bij een club?",
        "Wie zoekt altijd ruzie tijdens het uitgaan?",
        "Wie kotst als eerste na een avond drinken?",
        "Wie heeft de meeste bedpartners gehad?",
        "Wie heeft het bed gedeeld met de lelijkste persoon?",
        "Wie zou er als eerste betaler voor seks?",
        "Wie zou er als eerste geld vragen voor seks?",
        "Wie heeft er het triestste seksleven?",
        "Wie houdt er het meest van om aandacht te krijgen?",
        "Wie schept het meest op terwijl niemand onder de indruk is?",
        "Wie doet alsof ze geen drama willen maar veroorzaken het zelf?",
        "Wie reageert het snelst toxic tijdens ruzie?",
        "Wie overdrijft hun verhalen het meest?",
        "Wie heeft de grootste main character syndroom?",
        "Wie judged mensen het snelst?",
        "Wie praat het meest achter iemands rug om?",
        "Wie wordt het snelst jaloers?",
        "Wie doet het meest alsof ze onschuldig zijn?",
        "Wie zou het snelst teruggaan naar hun ex?",
        "Wie flirt het meest zonder intentie?",
        "Wie zoekt het meest bevestiging van anderen?",
        "Wie doet het snelst alsof het ze allemaal niet uit maakt?",
        "Wie is stiekem het meest manipulatief?",
        "Wie raakt het snelst obsessed met iemand?",
        "Wie houdt het meest van chaos?",
        "Wie zou het snelst een geheim verklappen na 2 drankjes?",
        "Wie heeft het grootste ego?",
        "Wie zou het snelst iemand vervangen?",
        "Wie maakt het snelst een situatie awkward?",
        "Wie liegt het beste?",
        "Wie doet het meest voor mannelijke/vrouwelijke aandacht?",
        "Wie heeft de meeste red flags?",
        "Wie zou het snelst een relatie saboteren?",
        "Wie denkt dat ze altijd gelijk hebben?",
        "Wie geniet stiekem het meest van drama?",
        "Wie heeft het laagste IQ?",
        "Wie is het minst emotioneel intelligent?",
        "Wie is het meest emotioneel intelligent?",
        "Wie laat het snelst iemand op afgeleverd staan?",
        "Wie zou het snelst een vriend vergeten zodra ze een relatie hebben?",
        "Wie speelt het meest hard to get?",
        "Wie denkt het snelst dat alles over hen gaat?",
        "Wie raakt het snelst verliefd?",
        "Wie kan het minst tegen kritiek?",
        "Wie probeert het hardst volwassen over te komen?",
        "Wie heeft de slechtste smaak in vrouwen/mannen?",
        "Wie zou het snelst terugkeren naar een toxic relatie?",
        "Wie houdt het meest van validatie?",
        "Wie neemt zichzelf het serieust?",
        "Wie zou het snelst een hele relatie geheim houden?",
        "Wie is het meest charismatisch?"
    ],
    MIX: []
};

// Populate MIX with all questions from all modes
PROMPTS.MIX = [
    ...PROMPTS.FAMILY,
    ...PROMPTS.ADULT,
    ...PROMPTS.DIRTY,
    ...PROMPTS.EXPOSING
];

export const NUMBER_PROMPTS: Record<GameMode, Record<Range, string[]>> = {
    FAMILY: {
        LOW: [
            "Hoeveel glazen water drink je per dag?",
            "Hoeveel uur slaap je gemiddeld?",
            "Hoeveel huisdieren heb je gehad in je leven?",
            "Hoeveel keer per week sport je?",
            "Hoeveel broers en zussen heb je?",
            "Hoeveel wekkers zet je 's avonds voor de volgende ochtend?",
            "Hoeveel kinderen zou je later willen hebben?",
            "Hoe laat zou je wakker worden als je morgen geen wekker zet (bijv. 9 voor 09:00)?",
            "Hoeveel echte vrienden heb je?",
            "Hoeveel planten heb je in je kamer?",
            "Hoeveel uur per week besteed je aan films/series kijken?",
            "Hoeveel snacks eet je gemiddeld per dag?",
            "Hoeveel familieleden spreek je maandelijks?",
            "Hoeveel keer per maand eet je fastfood?",
            "Hoeveel groepsapps heb je op mute staan?",
            "Hoevaak per week sla je ontbijt over?",
            "Hoevaak per week kook je zelf?"
        ],
        MEDIUM: [
            "Hoeveel paar schoenen bezit je?",
            "Hoeveel landen heb je bezocht?",
            "Van hoeveel familieleden ken je de verjaardag uit je hoofd?",
            "Wat is je gemiddelde schermtijd in uren per dag?",
            "Hoeveel uur per week luister je muziek?",
            "Hoeveel minuten duurt je gemiddelde douche?",
            "Om de hoeveel weken verschoon je je bed?"
        ],
        HIGH: [
            "Hoeveel minuten doe je erover om je klaar te maken in de ochtend?",
            "Hoeveel minuten te laat komen vind jij nog 'casual late' voor een feestje?",
            "Hoeveel apps staan er op je telefoon?",
            "Hoeveel ongelezen Whatsapp berichten heb je nu?",
            "Hoeveel stappen zet je gemiddeld op een dag?",
            "Hoeveel euro geef je gemiddeld uit aan boodschappen per maand?",
            "Hoeveel minuten duurt je gemiddelde douche?"
        ]
    },
    ADULT: {
        LOW: [
            "Hoeveel exen heb je?",
            "Hoeveel keer per maand bestel je eten?",
            "Hoeveel tattoos heb je?",
            "Hoeveel boetes heb je het afgelopen jaar gehad?",
            "Hoeveel koffie drink je per dag?",
            "Wat is het perfecte aantal biertjes voor een goede stapavond?",
            "Na hoeveel glazen alcohol heb je de volgende dag gegarandeerd een kater?",
            "Hoe vaak ben je dit jaar al dronken geweest?",
            "Na hoeveel biertjes ben je echt officieel dronken?",
            "Hoe vaak ben je in je leven echt verliefd geweest?",
            "Hoeveel collega's heb je waar je echt mee bevriend bent?",
            "Hoevaak ben je verliefd geweest op een klas/studiegenoot?",
            "Hoevaak heb je spijt gehad van een dronken zoen?",
            "Hoeveel datingapps heb je momenteel op je telefoon?",
            "Hoevaak heb je iemand afgewezen?",
            "Hoeveel drankjes bestel je tijdens het uitgaan?",
            "Hoevaak douche je per week?",
            "Hoeveel glazen wijn/bier drink je gemiddeld per week?"
        ],
        MEDIUM: [
            "Hoe oud was je toen je je eerste echte zoen kreeg?",
            "Hoeveel dates heb je het afgelopen jaar gehad?",
            "Hoeveel uur slaap neem je het liefst na een avond stappen?",
            "Hoeveel mensen heb je ooit serieus gedate?",
            "Hoeveel feestjes pak je gemiddeld per maand mee?",
            "Tot hoelaat houd je het gemiddeld vol op een nachtje uit (bijv. 3 voor 03:00)?",
            "Hoevaak heb je dit jaar gehuild?"
        ],
        HIGH: [
            "Hoeveel minuten zou je op je date wachten voordat je wegloopt?",
            "Na hoeveel minuten te laat komen op een date wordt het gênant?",
            "Hoeveel weeg je ongeveer (bijv. 75)?",
            "Wat is de maximale leeftijd van iemand met wie je zou daten?",
            "Wat is de minimale leeftijd van iemand met wie je zou daten?",
            "Wat is je kisscount (hoeveel mensen heb je gezoend)?",
            "Hoeveel euro geef je gemiddeld uit aan een avondje stappen?",
            "Hoeveel geld staat er op je spaarrekening (in honderden euro's)?",
            "Wat kostte het duurste kledingstuk dat je ooit hebt gekocht (in euro's)?",
            "Hoeveel euro geef je gemiddeld uit aan kleding per jaar?",
            "Wat is het langste dat je bent wakker gebleven in uren?",
            "Wat is het meest wat je hebt uitgegeven na een avond stappen?"
        ]
    },
    DIRTY: {
        LOW: [
            "Met hoeveel mensen zou je maximaal een bed delen?",
            "Hoeveel seksspeeltjes bezit je?",
            "Hoeveel keer per maand doe je aan zelfbevrediging?",
            "Hoeveel mensen heb je tegelijkertijd gedate?",
            "Hoeveel dagen heb je maximaal achter elkaar dezelfde onderbroek gedragen?",
            "Hoeveel dagen zou je niet kunnen douchen zonder dat het mensen opvalt?",
            "Hoe vaak masturbeer je gemiddeld per week?",
            "Na hoeveel minuten 'klaar zijn' met seks vind jij beschamend?",
            "Hoeveel mensen in deze kamer zouden je broertje/zusje mogen daten?",
            "Met hoeveel mensen heb je op 1 dag geflirt?",
            "Hoeveel bedpartners heb je gehad waar je nu spijt van hebt?",
            "Hoeveel mensen heb je ooit gezoend op één avond?"
        ],
        MEDIUM: [
            "Op welke leeftijd was je eerste keer?",
            "Hoeveel bedpartners heb je gehad (bodycount)?",
            "Van hoeveel bedpartners weet je de naam niet meer?",
            "Wat is het meeste aantal mensen dat je in één week hebt gezoend?",
            "Hoeveel seconden duurt de perfecte zoen?",
            "Na hoeveel maanden exclusief wordt het tijd voor een relatie?",
            "Hoeveel minuten duurde je langste zoen sessie?",
            "Hoeveel one-night stands heb je gehad?"
        ],
        HIGH: [
            "Hoeveel minuten duurt seks gemiddeld bij jou?",
            "Hoeveel mensen heb je in totaal gezoend?",
            "Hoe oud is de oudste persoon waar je ooit mee hebt gezoend?",
            "Hoeveel procent van je bedpartners ken je nog bij voornaam?",
            "Hoeveel nachten was je langste 'sex marathon'?"
        ]
    },
    EXPOSING: {
        LOW: [
            "Hoeveel leugens heb je vandaag al verteld?",
            "Hoeveel keer heb je iemands telefoon gecheckt zonder toestemming?",
            "Hoeveel mensen heb je geghost?",
            "Hoeveel ruzies heb je deze maand gehad?",
            "Hoeveel fake accounts heb je?",
            "Hoeveel keer heb je gecheckt wat je ex aan het doen is?",
            "Hoe vaak heb je iemand die minderjarig is stiekem knap gevonden?",
            "Hoeveel mensen in je contacten zouden opnemen als je ze nu om 3 uur 's nachts belt?",
            "Wat geef je de persoon RECHTS van je voor cijfer op uiterlijk (1-10)?",
            "Wat geef je de persoon LINKS van je voor cijfer op uiterlijk (1-10)?",
            "Wat geef je de persoon RECHTS van je voor cijfer op humor (1-10)?",
            "Wat geef je de persoon LINKS van je voor cijfer op humor (1-10)?",
            "Hoe ongemakkelijk vind je de persoon RECHTS van je (1-10)?",
            "Hoe ongemakkelijk vind je de persoon LINKS van je (1-10)?",
            "Wat voor cijfer geef je de kledingsmaak van de persoon RECHTS van je (1-10)?",
            "Wat voor cijfer geef je de kledingsmaak van de persoon LINKS van je (1-10)?",
            "Hoe groot is het ego van de persoon LINKS van je (1-10)?",
            "Hoe groot is het ego van de persoon RECHTS van je (1-10)?",
            "Hoe populair was de persoon LINKS van je vroeger op school (1-10)?",
            "Hoe populair was de persoon RECHTS van je vroeger op school (1-10)?",
            "Hoe goed is de muzieksmaak van de persoon LINKS van je (1-10)?",
            "Hoe goed is de muzieksmaak van de persoon RECHTS van je (1-10)?"
        ],
        MEDIUM: [
            "Hoeveel mensen heb je geblokkeerd op social media?",
            "Hoeveel mensen roddel je wekelijks over?",
            "Hoeveel keer heb je overgegeven door drank?"
        ],
        HIGH: [
            "Hoeveel geld heb je ooit gestolen (in euro's)?",
            "Hoeveel procent van je vrienden vertrouw je echt (0-100)?",
            "Hoeveel euro zou je minimaal moeten krijgen om een jaar geen seks te hebben?",
            "Hoeveel mensen heb je geghost in het afgelopen jaar?",
            "Hoeveel keer heb je iemands vertrouwen echt geschaad?"
        ]
    },
    MIX: {
        LOW: [],
        MEDIUM: [],
        HIGH: []
    }
};

// Populate MIX with all questions from all modes and ranges
(['LOW', 'MEDIUM', 'HIGH'] as Range[]).forEach(range => {
    NUMBER_PROMPTS.MIX[range] = [
        ...NUMBER_PROMPTS.FAMILY[range],
        ...NUMBER_PROMPTS.ADULT[range],
        ...NUMBER_PROMPTS.DIRTY[range],
        ...NUMBER_PROMPTS.EXPOSING[range]
    ];
});
